name: TTT-CLI-Local
description: 'Execute a scenario using the CLI'
branding:
  icon:  upload-cloud
  color: orange
author: 'BMC'
inputs:
  HCI Connection:
    description: 'The URL connect to HCI e.g. CW13.bmc.com:16196'
    required: true
  passticket:
    description: 'passticket input from the use e.g passticket'
    required: true
  testLocationPath:
    description: 'testLocationPath where test scenario to be executed e.g. C:\\actions-runner\\_work\\Topaz_Workbench_CLI_Test\\Topaz_Workbench_CLI_Test\\CLI_CWKTCOBX\\Tests\\'
    required: true
  configration:
    description: 'The runtime configuration used when connecting to TTT'
    required: true
outputs:
  description: 'The output shuld be stored in testLocationPath which user need to provide'
