# This is a basic workflow to help you get started with Actions for cli
name: Topaz for Total Test for input values

# Controls when the workflow will run
on:
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      hciconnection:
        # Host/IP adress input from users
        description: HCI Connection
        default: "CW13.bmc.com:16196"
        required: true
      passticket:
        # passticket input from the user.
        description: Pass Ticket
        default: "passticket"
        required: true
      testLocationPath:
        # passticket input from the user.
        description: Test Location Path
        default: "C:\\actions-runner\\_work\\Topaz_Workbench_CLI_Test\\Topaz_Workbench_CLI_Test\\CLI_CWKTCOBX\\Tests\\"
        required: true
      configration:
        # passticket input from the user.
        description: Configration
        default: "C:\\actions-runner\\_work\\Topaz_Workbench_CLI_Test\\Topaz_Workbench_CLI_Test\\TotalTestConfiguration"
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: self-hosted
   # runs-on: [self-hosted, ubuntu-latest]
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: git config --global core.longpaths true
      - name: Check HCI input value
        run: echo {{github.event.inputs.hciconnection}}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          clean: false
          path: ${{ github.workspace }}
          name: ${{ env.VERSION_MAJOR }}.${{ env.VERSION_MINOR }}

      # Runs a single command using the runners shell
      - name: Calling the CLI function
      #  run: cmd .\ExecuteCommand.bat
        run: cmd .\TotalTestFTCLI.bat -e ${{github.event.inputs.hciconnection}} ^ -${{github.event.inputs.passticket}} ^ -f ${{github.event.inputs.testLocationPath}} ^ -R -g TTTReport -G -v 6 -l CLI ^ -log DEBUG ^ -cfgdir ${{github.event.inputs.configration}}
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
